#!/bin/sh
# MyDegreePlan local launcher (macOS / Linux).   ./mdp.sh <command>     (see README.md)
#   start [--build]  generate secrets on first run, start everything, open the browser
#   stop             stop the app (your data is kept)
#   backup           stop, snapshot all data into ./backups, start again
#   restore <file>   replace all data with a snapshot made by `backup`
#   reset-password <email>
#   wipe             PERMANENTLY delete all data
#   package          (maintainer) build + save images into mydegreeplan-images.tar
#   update [apply]   (maintainer/diagnostic) check for, or install, an update. Students use the
#                    Update button inside the app instead.
#   logs | init
set -eu
cd "$(dirname "$0")"

ENV_FILE=.env
VOLUME=mdp_db_data
STATE_VOLUME=mdp_update_state
ACTIVE=.mdp-active-compose.yml
BUILD=0
USE_ACTIVE=0

fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_docker() {
  command -v docker >/dev/null 2>&1 || fail 'Docker is not installed. Install Docker Desktop (https://www.docker.com/products/docker-desktop), start it, and run this again.'
  docker info >/dev/null 2>&1 || fail 'Docker is installed but not running. Start Docker Desktop, wait until it says "running", then try again.'
  resolve_compose
}

# ── which compose file is current ────────────────────────────────────────────
# A bundle ships docker-compose.yml for the version it was built from. When the in-app
# updater installs a newer release it keeps that release's compose file in the
# mdp_update_state volume. Starting from the shipped file after that would quietly
# downgrade the app, so every compose call goes through dc, which prefers the volume's copy.
# `start --build` is the developer path and always uses the repo's own docker-compose.yml.
resolve_compose() {
  USE_ACTIVE=0
  [ "$BUILD" = 1 ] && return 0
  docker volume inspect "$STATE_VOLUME" >/dev/null 2>&1 || return 0   # never updated: use the shipped file
  # Any local updater image can read the volume. (A `docker image ls --filter reference=`
  # glob is not used: `*` does not match `/`, so it misses registry-qualified names.)
  img=$(docker image ls --format '{{.ID}} {{.Repository}}' | grep -E ' [^ ]*updater$' | head -n1 | cut -d' ' -f1)
  if [ -z "$img" ]; then
    # Not on disk any more: fall back to the updater image the shipped compose names (docker run pulls it).
    img=$(awk '/^  updater:[[:space:]]*$/{f=1;next} f&&/^  [^ ]/{exit} f&&/^[[:space:]]+image:/{print $2; exit}' docker-compose.yml)
  fi
  [ -n "$img" ] || fail 'An update has been installed but the updater image could not be found. Refusing to start an older version by mistake.'
  rc=0
  docker run --rm -v "$STATE_VOLUME:/s:ro" --entrypoint cat "$img" /s/current/docker-compose.yml > "$ACTIVE.tmp" 2>/dev/null || rc=$?
  if [ "$rc" = 0 ]; then
    mv "$ACTIVE.tmp" "$ACTIVE"; USE_ACTIVE=1
  elif [ "$rc" = 1 ]; then
    rm -f "$ACTIVE.tmp"                                                # no update applied yet
  else
    rm -f "$ACTIVE.tmp"
    fail 'Could not read the installed update state. Refusing to start an older version by mistake. Check that Docker is healthy and try again.'
  fi
}
dc() {
  if [ "$USE_ACTIVE" = 1 ]; then docker compose -f "$ACTIVE" --project-directory . "$@"; else docker compose "$@"; fi
}
# The updater needs to know the compose file the app was started from, so it can put the
# old version back if an update fails. Best effort: an update refuses to run without it.
save_launched_compose() {
  [ "$BUILD" = 1 ] && return 0
  if [ "$USE_ACTIVE" = 1 ]; then f="$ACTIVE"; else f=docker-compose.yml; fi
  docker cp "$f" mdp-updater:/state/launched.yml >/dev/null 2>&1 || true
}

# ── secrets ──────────────────────────────────────────────────────────────────
# tr -d '\r' guards against Windows builds of openssl (Git Bash) that emit CRLF.
b64url()  { openssl base64 -A | tr -d '\r\n' | tr '+/' '-_' | tr -d '='; }
secret()  { openssl rand -base64 "$1" | tr -d '\r\n' | tr '+/' '-_' | tr -d '='; }
jwt() {   # jwt <role> <secret>
  iat=$(date +%s); exp=$((iat + 315360000))   # 10 years; API keys, not login sessions
  hdr=$(printf '%s' '{"alg":"HS256","typ":"JWT"}' | b64url)
  pl=$(printf '{"role":"%s","iss":"supabase","iat":%s,"exp":%s}' "$1" "$iat" "$exp" | b64url)
  sig=$(printf '%s' "$hdr.$pl" | openssl dgst -sha256 -hmac "$2" -binary | b64url)
  printf '%s.%s.%s' "$hdr" "$pl" "$sig"
}
init_env() {
  [ -f "$ENV_FILE" ] && return 0
  command -v openssl >/dev/null 2>&1 || fail 'openssl is required to generate secrets.'
  if command -v docker >/dev/null 2>&1 && docker volume inspect "$VOLUME" >/dev/null 2>&1; then
    fail ".env is missing but a database already exists. A new .env would not match it. Restore the original .env (or run './mdp.sh wipe' to start over)."
  fi
  jwt_secret=$(secret 48)
  umask 077
  {
    echo '# Generated by mdp. Keep this file private and keep it with your data: it holds the'
    echo '# database password and signing key. Deleting it makes existing data unreadable.'
    echo "POSTGRES_PASSWORD=$(secret 24)"
    echo "JWT_SECRET=$jwt_secret"
    echo "ANON_KEY=$(jwt anon "$jwt_secret")"
    echo "SERVICE_ROLE_KEY=$(jwt service_role "$jwt_secret")"
    echo 'MDP_PORT=8080'
  } > "$ENV_FILE"
  echo 'Created .env with fresh secrets for this computer.'
}
port() { sed -n 's/^MDP_PORT=\([0-9]*\).*/\1/p' "$ENV_FILE" | head -n1; }

# Best effort: a missing or failing browser launcher must never fail `start`. `open` is only
# the macOS opener; on Debian/Ubuntu `open` is an unrelated program that exits non-zero.
open_url() {
  case "$(uname -s)" in
    Darwin) open "$1" >/dev/null 2>&1 || true ;;
    *) if command -v xdg-open >/dev/null 2>&1; then xdg-open "$1" >/dev/null 2>&1 || true; fi ;;
  esac
  return 0
}

# ── commands ─────────────────────────────────────────────────────────────────
IMAGE_TAR=mydegreeplan-images.tar
IMAGES='mydegreeplan/web:local mydegreeplan/setup:local mydegreeplan/db:local mydegreeplan/updater:local supabase/gotrue:v2.196.0 postgrest/postgrest:v14.17'

# Student bundles ship the images as a tar so nothing has to be built or downloaded.
import_images() {
  [ -f "$IMAGE_TAR" ] || return 0
  ! docker image inspect mydegreeplan/web:local >/dev/null 2>&1 || return 0
  echo 'Loading bundled images (one-time, may take a minute)...'
  docker load -i "$IMAGE_TAR" || fail 'Could not load mydegreeplan-images.tar.'
}

# Maintainer only (needs the full MDP checkout): build everything and save it for hand-off.
package() {
  need_docker
  docker compose build || fail 'Build failed.'
  docker compose pull --ignore-buildable || fail 'Pulling base images failed.'
  # shellcheck disable=SC2086
  docker save -o "$IMAGE_TAR" $IMAGES || fail 'docker save failed.'
  echo "Wrote $IMAGE_TAR. Zip it with docker-compose.yml, db/, mdp.cmd, mdp.ps1, mdp.sh and README.md (NOT .env or backups)."
}

start() {
  need_docker; init_env; import_images
  echo 'Starting MyDegreePlan (the first run downloads/builds images and can take several minutes)...'
  if [ "$BUILD" = 1 ]; then flag=--build; else flag=; fi
  # shellcheck disable=SC2086
  dc up -d $flag || { dc logs --tail 40 migrate auth rest web; fail 'Startup failed; the last log lines are above.'; }
  save_launched_compose
  echo 'Loading the course catalog...'
  waited=0
  while :; do
    s=$(docker inspect -f '{{.State.Status}}|{{.State.ExitCode}}' mdp-seed 2>/dev/null || true)
    case "$s" in
      'exited|0') break ;;
      exited\|*)  dc logs --tail 40 seed; fail 'Loading the course catalog failed.' ;;
    esac
    [ "$waited" -ge 240 ] && fail 'Timed out loading the course catalog. Check: ./mdp.sh logs'
    sleep 2; waited=$((waited + 2))
  done
  url="http://localhost:$(port)"
  echo "MyDegreePlan is running at $url  (only this computer can reach it)"
  open_url "$url"
}

backup() {
  need_docker
  [ -f "$ENV_FILE" ] || fail 'Nothing to back up yet (no .env).'
  mkdir -p backups
  name="mdp-backup-$(date +%Y%m%d-%H%M%S)"
  echo 'Stopping the app for a consistent snapshot...'
  dc down
  docker run --rm -v "$VOLUME:/data:ro" -v "$(pwd)/backups:/backup" alpine tar czf "/backup/$name.tar.gz" -C /data . || fail 'Backup failed.'
  cp "$ENV_FILE" "backups/$name.env"
  echo "Backup written: backups/$name.tar.gz (+ $name.env)"
  echo 'These files contain everything in the plan, unencrypted. Store them somewhere private.'
  start
}

restore() {
  need_docker
  [ -n "${1:-}" ] && [ -f "$1" ] || fail 'Usage: ./mdp.sh restore <path to a .tar.gz made by backup>'
  dir=$(cd "$(dirname "$1")" && pwd); base=$(basename "$1")
  envbak="$dir/${base%.tar.gz}.env"
  printf 'This REPLACES all current data with the backup. Type RESTORE to continue: '; read -r ans
  [ "$ans" = RESTORE ] || fail 'Cancelled.'
  dc down
  docker volume rm -f "$VOLUME" >/dev/null
  docker volume create "$VOLUME" >/dev/null
  docker run --rm -v "$VOLUME:/data" -v "$dir:/backup:ro" alpine tar xzf "/backup/$base" -C /data || fail 'Restore failed.'
  if [ -f "$envbak" ]; then
    [ -f "$ENV_FILE" ] && cp "$ENV_FILE" "$ENV_FILE.bak"
    cp "$envbak" "$ENV_FILE"
    echo 'Restored the matching .env as well.'
  else
    echo "No $(basename "$envbak") next to the backup; keeping the current .env. If the passwords differ, copy the original .env back."
  fi
  start
}

reset_password() {
  need_docker
  [ -n "${1:-}" ] || fail 'Usage: ./mdp.sh reset-password <email>'
  printf 'New password (min 8 characters): '; stty -echo 2>/dev/null || true; read -r pw; stty echo 2>/dev/null || true; echo
  [ "${#pw}" -ge 8 ] || fail 'Password must be at least 8 characters.'
  esc() { printf '%s' "$1" | sed "s/'/''/g"; }
  email=$(esc "$1"); pw=$(esc "$pw")
  printf "UPDATE auth.users SET encrypted_password = extensions.crypt('%s', extensions.gen_salt('bf')) WHERE lower(email) = lower('%s');\n" "$pw" "$email" \
    | dc exec -T db psql -U postgres -d postgres -q -f - >/dev/null
  n=$(printf "SELECT count(*) FROM auth.users WHERE lower(email) = lower('%s');\n" "$email" \
    | dc exec -T db psql -U postgres -d postgres -q -t -A -f -)
  [ "$(printf '%s' "$n" | tr -d '[:space:]')" != 0 ] || fail 'No account with that email.'
  echo 'Password updated.'
}

# Talks to the updater over its container-only listener (no login needed: `docker exec`
# already means full Docker access).
update() {
  need_docker
  if [ "${1:-}" = apply ]; then sub=apply; else sub=check; fi
  docker exec mdp-updater node src/main.js cli "$sub" || fail 'The updater did not accept that. Is the app running? (./mdp.sh start)'
  [ "$sub" = check ] && echo 'If an update is available, run: ./mdp.sh update apply'
  return 0
}

wipe() {
  need_docker
  printf 'This PERMANENTLY deletes every plan and account on this computer. Type DELETE to continue: '; read -r ans
  [ "$ans" = DELETE ] || fail 'Cancelled.'
  dc down -v
  echo 'All data deleted.'
}

cmd="${1:-start}"; [ $# -gt 0 ] && shift
if [ "$cmd" = start ] && [ "${1:-}" = "--build" ]; then BUILD=1; fi
case "$cmd" in
  start)          start "$@" ;;
  stop)           need_docker; dc down; echo 'Stopped. Your data is kept.' ;;
  backup)         backup ;;
  restore)        restore "$@" ;;
  reset-password) reset_password "$@" ;;
  wipe)           wipe ;;
  update)         update "$@" ;;
  package)        package ;;
  logs)           need_docker; dc logs --tail 100 ;;
  init)           init_env ;;
  *)              fail "Unknown command '$cmd'. Commands: start, stop, backup, restore, reset-password, wipe, update, package, logs" ;;
esac
