// Release building blocks, shared by the CLIs and the tests. No I/O in here.
import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, sign, verify } from 'node:crypto'
import { parse, stringify } from 'yaml'

export const DIGEST_RE = /@sha256:[0-9a-f]{64}$/
export const sha256Hex = (data) => createHash('sha256').update(data).digest('hex')

// Every image the dev compose references must have an entry in `imageMap`
// ({ "<image as written in docker-compose.yml>": "<name>@sha256:<digest>" }); a
// missing or unpinned entry is an error, never a silent fallback to a floating tag.
export function makeReleaseCompose(devText, { imageMap, version, sequence, updateUrl }) {
  const doc = parse(devText, { merge: true })
  if (!doc?.services?.updater) throw new Error('docker-compose.yml has no updater service')
  delete doc['x-setup']   // only carried the YAML anchor the dev file shares between migrate and seed
  for (const [name, svc] of Object.entries(doc.services)) {
    delete svc.build
    const pinned = imageMap[svc.image]
    if (!pinned) throw new Error(`no pinned image supplied for ${name} (${svc.image})`)
    if (!DIGEST_RE.test(pinned)) throw new Error(`image for ${name} is not digest-pinned: ${pinned}`)
    svc.image = pinned
  }
  Object.assign(doc.services.updater.environment, {
    MDP_VERSION: String(version),
    MDP_SEQUENCE: String(sequence),
    MDP_UPDATE_URL: updateUrl,
  })
  const header = [
    '# GENERATED by release-tools/make-release.mjs — do not edit.',
    `# MyDegreePlan ${version} (release sequence ${sequence}). Every image is pinned by digest.`,
    '',
  ].join('\n')
  return header + stringify(doc, { lineWidth: 0 })
}

export function makeManifest({ version, sequence, minSequence = 0, notes = '', composeText, images = {}, sources = {}, releasedAt = new Date().toISOString() }) {
  return JSON.stringify({
    schema: 1,
    version,
    sequence,
    min_sequence: minSequence,
    released_at: releasedAt,
    notes,
    compose: { file: 'docker-compose.yml', sha256: sha256Hex(Buffer.from(composeText)) },
    images,
    sources,
  }, null, 2) + '\n'
}

export function generateSigningKey() {
  const { publicKey, privateKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' })
  return {
    publicPem: publicKey.export({ type: 'spki', format: 'pem' }),
    privatePem: privateKey.export({ type: 'pkcs8', format: 'pem' }),
  }
}

// base64 of the DER ECDSA-SHA256 signature over the exact bytes — what the updater verifies.
export function signBytes(bytes, privatePem) {
  return sign('sha256', bytes, createPrivateKey(privatePem)).toString('base64') + '\n'
}

export function verifyBytes(bytes, signature, publicPem) {
  try { return verify('sha256', bytes, createPublicKey(publicPem), Buffer.from(signature.trim(), 'base64')) } catch { return false }
}
